stages:
  - testing
  - reports

docker_job:
  stage: testing
  tags:
    - docker
  image: python:3.10-alpine
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --alluredir=./allure-results tests/

  allow_failure: true
  artifacts:
    when: always
    paths:
      - ./allure-results
    expire_in: 1 day

allure_job:
  stage: reports
  tags:
    - docker
  image: frankescobar/allure-docker-service
  script:
     - allure generate -c ./allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always

